LCAM-1190
ministryofjustice/laa-maat-orchestration pull request #91
Opened 2024-02-01 16:58 UTC by skasthuri36326

## What

[LCAM-1190](https://dsdmoj.atlassian.net/browse/LCAM-1190)

Describe what you did and why.
- Migrated Generic Validation Checks in the pre_update_checks Stored Procedure to the Orchestration Service

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2024-02-05 19:07 UTC, venkat980 requested changes

2024-02-05 19:07 UTC, venkat980 commented on maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/RepOrderDTO.java
> +    private List<FinancialAssessmentDTO> financialAssessments = new ArrayList<>();
I think this FinancialAssessmentDTO is different, and this needs to be copied across from MAAT API.

2024-02-05 19:07 UTC, venkat980 commented on maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/RepOrderDTO.java
> +    private List<IOJAppealDTO> iojAppeal = new ArrayList<>();
Same here, IOJAppealDTO and ContributionsDTO are different and needs to be moved across from API. Lets create a new folder 'api' under dto/maat and move all the MAAT Court Data API's to this folder.

2024-02-06 10:14 UTC, skasthuri36326 commented on maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
> +        boolean isUpdateAllowedOnApplication = statusDTO.getUpdateAllowed();
My understanding is pre update checks are for an existing application. So there will always be a status associated with the application?

2024-02-06 11:27 UTC, venkat980 approved these changes

2024-02-06 11:29 UTC, merged